.TH RECYCLE 1 "March 2025" "Version 1.0" "Recycle Script Manual"

.SH NAME
recycle \- move files to a recycle bin directory with Git tracking

.SH SYNOPSIS
.B recycle
[\fIoptions\fR] <file1> <file2> ...

.SH DESCRIPTION
The \fBrecycle\fR script moves specified files into a designated recycle bin directory while tracking changes using Git. It is designed for preserving temporary or one-time-use files that may be useful later.

.SH OPTIONS
.TP
\fB-m\fR "message"
Specify a custom commit message for Git. If not provided, a default message will be generated using the current date and time. The list of files is always included in the commit message body.

.SH USAGE EXAMPLES
.TP
Recycle a single file:
.B recycle /path/to/file.txt

.TP
Recycle multiple files with a custom commit message:
.B recycle -m \(dqscraped example.com\(dq /path/to/scrape_example.sh /path/to/post_process_example.sh


.TP
Recycle multiple files with the default commit message:
.B recycle /path/to/file1.txt /path/to/file2.txt

.SH DEFAULT COMMIT MESSAGE FORMAT
.TP
The head line defaults to a timestamp in the format:
.B [YYYY-MM-DD-HHmm.ss]

.TP
In all cases, the content paragraph will contain the list of files:
.B /original/file/path/of/first/input.file
.br
.B ...
.br
.B /original/file/path/of/last/input.file

.SH REPOSITORY STRUCTURE
The main branch contains development for the \fBrecycle\fR script itself. Workstation-specific branches store recycled items for individual systems.

.SH LICENSES AND SHARING PHILOSOPHY
The \fBrecycle\fR script is licensed under the Artistic License 2.0.
Recycled items are considered public domain unless explicitly stated otherwise.

.SH AUTHOR
Hildigerr Vergaray
.br
https://github.com/hildigerr/recycle.bin
