#!/bin/sh

# Retrieved Listings of Pages via command such as:
# curl https://mondaymandala.com/adult-coloring-pages/ | grep -o '<a href=".*" target="_blank"[^>]*>[^>]*[0-9]* Page[^>]*a>' | sed 's|<a href=\("[^"]*"\)[^>]*>\([^(]*\) .*|work "\2" \1|' >> adults
# Partially selected paths, then stripped them back resulting in files such as 'adults' and 'adults.strip'
# Unprocessed category files went into 'todo' dir, all striped and todo files merged into a sorted uniq list
# Selected Path's for Pages via: process_paths.sh 'list.sort.uniq'
# Sorted resulting file, eliminated dupes, and verified all urls present via : url_search.awk with each residual file
# Appended result to this file...

ROOT="${PWD}"

scrape () {
  if [ $# -lt 2 ]; then echo "usage: ${FUNCNAME} ext url"; return; fi
  curl "$2" | grep -o "\"[^\" ]\\+\.${1}\"" | sort | uniq | xargs wget -nc {}
}

work () {
  local next_dir="${ROOT}/${1}" && shift
  mkdir -p "${next_dir}" && cd "${next_dir}"
  echo -e "${PWD} ==\n${next_dir}:"
  for each in $@; do
    scrape pdf "${each}"
  done
}

work "Art/Clock Faces" "https://mondaymandala.com/printable-clock-faces/"
work "Art/Dreamcatcher" "https://mondaymandala.com/dreamcatcher-coloring-pages/"
work "Art/Fashion" "https://mondaymandala.com/dress-coloring-pages/"
work "Art/Fashion" "https://mondaymandala.com/fashion-coloring-pages/"
work "Art/Fashion" "https://mondaymandala.com/nike-coloring-pages/"
work "Art/Fashion" "https://mondaymandala.com/shoe-coloring-pages/"
work "Art/Geometric" "https://mondaymandala.com/geometric-coloring-pages/"
work "Art/Hearts" "https://mondaymandala.com/heart-coloring-pages/"
work "Art/Hippie" "https://mondaymandala.com/hippie-coloring-pages/"
work "Art/Hippie" "https://mondaymandala.com/peace-coloring-pages/"
work "Art/Hippie" "https://mondaymandala.com/trippy-coloring-pages/"
work "Art/Lisa Frank" "https://mondaymandala.com/lisa-frank-coloring-pages/"
work "Art/Mandala" "https://mondaymandala.com/m/"
work "Art/Mosaic" "https://mondaymandala.com/mosaic-coloring-pages/"
work "Art/Patterns" "https://mondaymandala.com/pattern-coloring-pages/"
work "Art/Rainbow" "https://mondaymandala.com/rainbow-coloring-pages/"
work "Art/Stained Glass" "https://mondaymandala.com/stained-glass-coloring-pages/"
work "Art/Sugar Skulls" "https://mondaymandala.com/sugar-skull-coloring-pages/"
work "Art/Tattoo" "https://mondaymandala.com/tattoo-coloring-pages/"
work "Art/Zentangle" "https://mondaymandala.com/zentangle-coloring-pages/"
work "Celebrities/Beyonce" "https://mondaymandala.com/beyonce-coloring-pages/"
work "Celebrities/Billie Eilish" "https://mondaymandala.com/billie-eilish-coloring-pages/"
work "Celebrities/Elvis" "https://mondaymandala.com/elvis-coloring-pages/"
work "Celebrities/Taylor Swift" "https://mondaymandala.com/taylor-swift-coloring-pages/"
work "Celebrities/The Rock" "https://mondaymandala.com/the-rock-coloring-pages/"
work "Comics/DC/Batman" "https://mondaymandala.com/batman-coloring-pages/"
work "Comics/DC/Catwoman" "https://mondaymandala.com/catwoman-coloring-pages/"
work "Comics/DC/Flash" "https://mondaymandala.com/flash-coloring-pages/"
work "Comics/DC/Green Lantern" "https://mondaymandala.com/green-lantern-coloring-pages/"
work "Comics/DC/Harley Quinn" "https://mondaymandala.com/harley-quinn-coloring-pages/"
work "Comics/DC/Joker" "https://mondaymandala.com/joker-coloring-pages/"
work "Comics/DC/Justice League" "https://mondaymandala.com/justice-league-coloring-pages/"
work "Comics/DC/Supergirl" "https://mondaymandala.com/supergirl-coloring-pages/"
work "Comics/DC/Superman" "https://mondaymandala.com/superman-coloring-pages/"
work "Comics/DC/Wonder Woman" "https://mondaymandala.com/wonder-woman-coloring-pages/"
work "Comics/Manga/Demon Slayer" "https://mondaymandala.com/demon-slayer-coloring-pages/"
work "Comics/Manga/Demon Slayer" "https://mondaymandala.com/nezuko-coloring-pages/"
work "Comics/Manga/Doraemon" "https://mondaymandala.com/doraemon-coloring-pages/"
work "Comics/Manga/My Hero Academia" "https://mondaymandala.com/my-hero-academia-coloring-pages/"
work "Comics/Manga/Naruto" "https://mondaymandala.com/naruto-coloring-pages/"
work "Comics/Manga/Sailor Moon" "https://mondaymandala.com/sailor-moon-coloring-pages/"
work "Comics/Marvel/Aquaman" "https://mondaymandala.com/aquaman-coloring-pages/"
work "Comics/Marvel/Avengers" "https://mondaymandala.com/marvel-avengers-coloring-pages/"
work "Comics/Marvel/Big Hero 6" "https://mondaymandala.com/big-hero-6-coloring-pages/"
work "Comics/Marvel/Black Panther" "https://mondaymandala.com/black-panther-coloring-pages/"
work "Comics/Marvel/Captain America" "https://mondaymandala.com/captain-america-coloring-pages/"
work "Comics/Marvel/Carnage" "https://mondaymandala.com/carnage-coloring-pages/"
work "Comics/Marvel/Deadpool" "https://mondaymandala.com/deadpool-coloring-pages/"
work "Comics/Marvel/Doctor Strange" "https://mondaymandala.com/doctor-strange-coloring-pages/"
work "Comics/Marvel/Ghost Rider" "https://mondaymandala.com/ghost-rider-coloring-pages/"
work "Comics/Marvel/Green Goblin" "https://mondaymandala.com/green-goblin-coloring-pages/"
work "Comics/Marvel/Groot" "https://mondaymandala.com/groot-coloring-pages/"
work "Comics/Marvel/Hulk" "https://mondaymandala.com/hulk-coloring-pages/"
work "Comics/Marvel/Iron Man" "https://mondaymandala.com/iron-man-coloring-pages/"
work "Comics/Marvel/Iron Spider" "https://mondaymandala.com/iron-spider-coloring-pages/"
work "Comics/Marvel/Loki" "https://mondaymandala.com/loki-coloring-pages/"
work "Comics/Marvel/Spider-Gwen" "https://mondaymandala.com/spider-gwen-coloring-pages/"
work "Comics/Marvel/Spider-Man" "https://mondaymandala.com/miles-morales-coloring-pages/"
work "Comics/Marvel/Spider-Man" "https://mondaymandala.com/spider-man-coloring-pages/"
work "Comics/Marvel/Thor" "https://mondaymandala.com/thor-coloring-pages/"
work "Comics/Marvel/Venom" "https://mondaymandala.com/venom-coloring-pages/"
work "Comics/Marvel/Wolverine" "https://mondaymandala.com/wolverine-coloring-pages/"
work "Comics/Marvel/X-Men" "https://mondaymandala.com/x-men-coloring-pages/"
work "Comics/TMNT" "https://mondaymandala.com/ninja-turtles-coloring-pages/"
work "Disney/Classic/101 Dalmatians" "https://mondaymandala.com/101-dalmatians-coloring-pages/"
work "Disney/Classic/Alice in Wonderland" "https://mondaymandala.com/alice-in-wonderland-coloring-pages/"
work "Disney/Classic/Aristocats" "https://mondaymandala.com/aristocats-coloring-pages/"
work "Disney/Classic/Bambi" "https://mondaymandala.com/bambi-coloring-pages/"
work "Disney/Classic/Cinderalla" "https://mondaymandala.com/cinderella-coloring-pages/"
work "Disney/Classic/Daisy" "https://mondaymandala.com/daisy-duck-coloring-pages/"
work "Disney/Classic/Donald" "https://mondaymandala.com/donald-duck-coloring-pages/"
work "Disney/Classic/Dumbo" "https://mondaymandala.com/dumbo-coloring-pages/"
work "Disney/Classic/Goofy" "https://mondaymandala.com/goofy-coloring-pages/"
work "Disney/Classic/Jungle Book" "https://mondaymandala.com/jungle-book-coloring-pages/"
work "Disney/Classic/Lady and the Tramp" "https://mondaymandala.com/lady-and-the-tramp-coloring-pages/"
work "Disney/Classic/Peter Pan" "https://mondaymandala.com/peter-pan-coloring-pages/"
work "Disney/Classic/Pinocchio" "https://mondaymandala.com/pinocchio-coloring-pages/"
work "Disney/Classic/Sleeping Beauty" "https://mondaymandala.com/maleficent-coloring-pages/"
work "Disney/Classic/Sleeping Beauty" "https://mondaymandala.com/sleeping-beauty-coloring-pages/"
work "Disney/Classic/Snow White" "https://mondaymandala.com/snow-white-coloring-pages/"
work "Disney/Classic/Winnie the Pooh" "https://mondaymandala.com/eeyore-coloring-pages/"
work "Disney/Classic/Winnie the Pooh" "https://mondaymandala.com/piglet-coloring-pages/"
work "Disney/Classic/Winnie the Pooh" "https://mondaymandala.com/tigger-coloring-pages/"
work "Disney/Modern/Encanto" "https://mondaymandala.com/encanto-coloring-pages/"
work "Disney/Modern/Frozen" "https://mondaymandala.com/anna-coloring-pages/"
work "Disney/Modern/Frozen" "https://mondaymandala.com/elsa-coloring-pages/"
work "Disney/Modern/Frozen" "https://mondaymandala.com/frozen-coloring-pages/"
work "Disney/Modern/Frozen" "https://mondaymandala.com/olaf-coloring-pages/"
work "Disney/Modern/Lilo and Stitch" "https://mondaymandala.com/lilo-stitch-coloring-pages/"
work "Disney/Modern/Moana" "https://mondaymandala.com/moana-coloring-pages/"
work "Disney/Modern/Princess and the Frog" "https://mondaymandala.com/princess-and-frog-coloring-pages/"
work "Disney/Modern/Raya and the Last Dragon" "https://mondaymandala.com/raya-last-dragon-coloring-pages/"
work "Disney/Modern/Tangled" "https://mondaymandala.com/tangled-coloring-pages/"
work "Disney/Pixar/Brave" "https://mondaymandala.com/merida-coloring-pages/"
work "Disney/Pixar/Cars" "https://mondaymandala.com/disney-cars-coloring-pages/"
work "Disney/Pixar/Coco" "https://mondaymandala.com/coco-coloring-pages/"
work "Disney/Pixar/Elemental" "https://mondaymandala.com/elemental-coloring-pages/"
work "Disney/Pixar/etc" "https://mondaymandala.com/pixar-coloring-pages/"
work "Disney/Pixar/Finding Nemo" "https://mondaymandala.com/finding-nemo-coloring-pages/"
work "Disney/Pixar/Incredibles" "https://mondaymandala.com/incredibles-coloring-pages/"
work "Disney/Pixar/Inside Out" "https://mondaymandala.com/inside-out-coloring-pages/"
work "Disney/Pixar/Luca" "https://mondaymandala.com/luca-coloring-pages/"
work "Disney/Pixar/Monsters Inc" "https://mondaymandala.com/monsters-inc-coloring-pages/"
work "Disney/Pixar/Toy Story" "https://mondaymandala.com/buzz-lightyear-coloring-pages/"
work "Disney/Pixar/Toy Story" "https://mondaymandala.com/toy-story-coloring-pages/"
work "Disney/Pixar/Up" "https://mondaymandala.com/up-coloring-pages/"
work "Disney/Pixar/Wreck-It Ralph" "https://mondaymandala.com/wreck-it-ralph-coloring-pages/"
work "Disney/Renaissance/Aladdin" "https://mondaymandala.com/aladdin-coloring-pages/"
work "Disney/Renaissance/Beuty and the Beast" "https://mondaymandala.com/beauty-and-the-beast-coloring-pages/"
work "Disney/Renaissance/Beuty and the Beast" "https://mondaymandala.com/belle-coloring-pages/"
work "Disney/Renaissance/Hercules" "https://mondaymandala.com/hercules-coloring-pages/"
work "Disney/Renaissance/Lion King" "https://mondaymandala.com/lion-guard-coloring-pages/"
work "Disney/Renaissance/Lion King" "https://mondaymandala.com/lion-king-coloring-pages/"
work "Disney/Renaissance/Little Mermaid" "https://mondaymandala.com/ariel-coloring-pages/"
work "Disney/Renaissance/Mulan" "https://mondaymandala.com/mulan-coloring-pages/"
work "Disney/Renaissance/Pocahontas" "https://mondaymandala.com/pocahontas-coloring-pages/"
work "Disney/Renaissance/Tarzan" "https://mondaymandala.com/tarzan-coloring-pages/"
work "Fantasy/Alien" "https://mondaymandala.com/alien-coloring-pages/"
work "Fantasy/Angel" "https://mondaymandala.com/angel-coloring-pages/"
work "Fantasy/Dragon" "https://mondaymandala.com/dragon-coloring-pages/"
work "Fantasy/Fairy" "https://mondaymandala.com/fairy-coloring-pages/"
work "Fantasy/Gnome" "https://mondaymandala.com/gnome-coloring-pages/"
work "Fantasy/Knight" "https://mondaymandala.com/knight-coloring-pages/"
work "Fantasy/Medusa" "https://mondaymandala.com/medusa-coloring-pages/"
work "Fantasy/Mermaid" "https://mondaymandala.com/mermaid-coloring-pages/"
work "Fantasy/Tooth Fairy" "https://mondaymandala.com/tooth-fairy-coloring-pages/"
work "Fantasy/Unicorn" "https://mondaymandala.com/unicorn-coloring-pages/"
work "Fantasy/Wings of Fire" "https://mondaymandala.com/wings-of-fire-coloring-pages/"
work "Fantasy/Wizard" "https://mondaymandala.com/wizard-coloring-pages/"
work "Food/Cake" "https://mondaymandala.com/cake-coloring-pages/"
work "Food/Drinks" "https://mondaymandala.com/boba-tea-coloring-pages/"
work "Food/Drinks" "https://mondaymandala.com/coffee-coloring-pages/"
work "Food/Drinks" "https://mondaymandala.com/hot-chocolate-coloring-pages/"
work "Food/Drinks" "https://mondaymandala.com/starbucks-coloring-pages/"
work "Games/About Me" "https://mondaymandala.com/all-about-me-worksheets/"
work "Games/Arcade/Sonic" "https://mondaymandala.com/knuckles-coloring-pages/"
work "Games/Arcade/Sonic" "https://mondaymandala.com/shadow-sonic-coloring-pages/"
work "Games/Arcade/Sonic" "https://mondaymandala.com/super-sonic-coloring-pages/"
work "Games/Arcade/Sonic" "https://mondaymandala.com/tails-coloring-pages/"
work "Games/Mobile/Among Us" "https://mondaymandala.com/among-us-coloring-pages/"
work "Games/Mobile/Angry Birds" "https://mondaymandala.com/angry-birds-coloring-pages/"
work "Games/Mobile/Tamogotchi" "https://mondaymandala.com/tamagotchi-coloring-pages/"
work "Games/Mobile/Toca Boca" "https://mondaymandala.com/toca-boca-coloring-pages/"
work "Games/Nintendo/Animal Crossing" "https://mondaymandala.com/animal-crossing-coloring-pages/"
work "Games/Nintendo/Mario" "https://mondaymandala.com/bowser-coloring-pages/"
work "Games/Nintendo/Mario" "https://mondaymandala.com/princess-daisy-coloring-pages/"
work "Games/Nintendo/Mario" "https://mondaymandala.com/princess-peach-coloring-pages/"
work "Games/Nintendo/Mario" "https://mondaymandala.com/rosalina-coloring-pages/"
work "Games/Nintendo/Mario Kart" "https://mondaymandala.com/mario-kart-coloring-pages/"
work "Games/Other/Plants Vs Zombies" "https://mondaymandala.com/plants-vs-zombies-coloring-pages/"
work "Games/Other/Rainbow Friends" "https://mondaymandala.com/rainbow-friends-coloring-pages/"
work "Games/Shooters/Call of Duty" "https://mondaymandala.com/call-of-duty-coloring-pages/"
work "Holiday/America" "https://mondaymandala.com/american-flag-coloring-pages/"
work "Holiday/Christmas/Grinch" "https://mondaymandala.com/grinch-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/candy-cane-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-coloring-pages-for-adults/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-lights-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-mandala-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-ornament-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-present-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-stockings-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-tree-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/christmas-wreath-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/disney-christmas-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/elf-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/elf-on-the-shelf-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/gingerbread-house-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/gingerbread-man-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/mistletoe-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/north-pole-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/nutcracker-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/reindeer-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/rudolph-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/santa-coloring-pages/"
work "Holiday/Christmas" "https://mondaymandala.com/snowman-coloring-pages/"
work "Holiday/Christmas/Wordsearch" "https://mondaymandala.com/christmas-word-searches/"
work "Holiday/Easter" "https://mondaymandala.com/disney-easter-coloring-pages/"
work "Holiday/Easter" "https://mondaymandala.com/easter-bunny-coloring-pages/"
work "Holiday/Easter" "https://mondaymandala.com/easter-egg-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/disney-halloween-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/ghost-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/grim-reaper-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/halloween-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/halloween-mandala-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/haunted-house-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/horror-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/jack-o-lantern-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/monster-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/mummy-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/pumpkin-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/scarecrow-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/skeleton-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/vampire-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/werewolf-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/witch-coloring-pages/"
work "Holiday/Halloween" "https://mondaymandala.com/zombie-coloring-pages/"
work "Holiday/Hanukkah" "https://mondaymandala.com/hanukkah-coloring-pages/"
work "Holiday/Seasons/Fall" "https://mondaymandala.com/fall-coloring-pages/"
work "Holiday/Seasons/Fall" "https://mondaymandala.com/fall-leaves-coloring-pages/"
work "Holiday/Seasons/Spring" "https://mondaymandala.com/spring-coloring-pages/"
work "Holiday/Seasons/Spring" "https://mondaymandala.com/spring-coloring-pages/"
work "Holiday/Seasons/Summer" "https://mondaymandala.com/summer-coloring-pages/"
work "Holiday/Seasons/Summer" "https://mondaymandala.com/sun-coloring-pages/"
work "Holiday/Seasons/Winter" "https://mondaymandala.com/snowflake-coloring-pages/"
work "Holiday/Seasons/Winter" "https://mondaymandala.com/winter-coloring-pages/"
work "Holiday/St Patricks Day" "https://mondaymandala.com/st-patricks-day-coloring-pages/"
work "Holiday/Thanksgiving" "https://mondaymandala.com/thanksgiving-coloring-pages/"
work "Movies/Beetlejuice" "https://mondaymandala.com/beetlejuice-coloring-pages/"
work "Movies/Coraline" "https://mondaymandala.com/coraline-coloring-pages/"
work "Movies/Corpse Bride" "https://mondaymandala.com/corpse-bride-coloring-pages/"
work "Movies/Frankenstein" "https://mondaymandala.com/frankenstein-coloring-pages/"
work "Movies/Ghostbusters" "https://mondaymandala.com/ghostbusters-coloring-pages/"
work "Movies/Godzilla" "https://mondaymandala.com/godzilla-coloring-pages/"
work "Movies/Harry Potter" "https://mondaymandala.com/harry-potter-coloring-pages/"
work "Movies/Hocus Pocus" "https://mondaymandala.com/hocus-pocus-coloring-pages/"
work "Movies/Home Alone" "https://mondaymandala.com/home-alone-coloring-pages/"
work "Movies/Hotel Transylvania" "https://mondaymandala.com/hotel-transylvania-coloring-pages/"
work "Movies/How To Train Your Dragon" "https://mondaymandala.com/how-to-train-your-dragon-coloring-pages/"
work "Movies/Ice Age" "https://mondaymandala.com/ice-age-coloring-pages/"
work "Movies/IT" "https://mondaymandala.com/pennywise-coloring-pages/"
work "Movies/Jurassic Park" "https://mondaymandala.com/jurassic-park-coloring-pages/"
work "Movies/King Kong" "https://mondaymandala.com/king-kong-coloring-pages/"
work "Movies/Kung Fu Panda" "https://mondaymandala.com/kung-fu-panda-coloring-pages/"
work "Movies/Land Before Time" "https://mondaymandala.com/land-before-time-coloring-pages/"
work "Movies/Madagascar" "https://mondaymandala.com/madagascar-coloring-pages/"
work "Movies/Minions" "https://mondaymandala.com/minion-coloring-pages/"
work "Movies/Nightmare Before Christmas" "https://mondaymandala.com/nightmare-before-christmas-coloring-pages/"
work "Movies/Shrek" "https://mondaymandala.com/shrek-coloring-pages/"
work "Movies/Sing" "https://mondaymandala.com/sing-coloring-pages/"
work "Movies/Studio Ghibli" "https://mondaymandala.com/studio-ghibli-coloring-pages/"
work "Movies/Titanic" "https://mondaymandala.com/titanic-coloring-pages/"
work "Movies/Trolls" "https://mondaymandala.com/trolls-coloring-pages/"
work "Movies/Zootopia" "https://mondaymandala.com/zootopia-coloring-pages/"
work "Nature/Animals/Bats" "https://mondaymandala.com/bat-coloring-pages/"
work "Nature/Animals/Bears" "https://mondaymandala.com/polar-bear-coloring-pages/"
work "Nature/Animals/Birds" "https://mondaymandala.com/owl-coloring-pages/"
work "Nature/Animals/Birds" "https://mondaymandala.com/parrot-coloring-pages/"
work "Nature/Animals/Birds" "https://mondaymandala.com/penguin-coloring-pages/"
work "Nature/Animals/Birds" "https://mondaymandala.com/raven-coloring-pages/"
work "Nature/Animals/Birds" "https://mondaymandala.com/turkey-coloring-pages/"
work "Nature/Animals/Bovidae" "https://mondaymandala.com/bull-coloring-pages/"
work "Nature/Animals/Bovidae" "https://mondaymandala.com/goat-coloring-pages/"
work "Nature/Animals/Canine" "https://mondaymandala.com/dog-coloring-pages/"
work "Nature/Animals/Canine" "https://mondaymandala.com/fox-coloring-pages/"
work "Nature/Animals/Canine" "https://mondaymandala.com/husky-coloring-pages/"
work "Nature/Animals/Canine" "https://mondaymandala.com/puppy-coloring-pages/"
work "Nature/Animals/Elephant" "https://mondaymandala.com/elephant-coloring-pages/"
work "Nature/Animals/Equine" "https://mondaymandala.com/horse-coloring-pages/"
work "Nature/Animals/Feline" "https://mondaymandala.com/cat-coloring-pages/"
work "Nature/Animals/Feline" "https://mondaymandala.com/kitten-coloring-pages/"
work "Nature/Animals/Insects" "https://mondaymandala.com/bumblebee-coloring-pages/"
work "Nature/Animals/Insects" "https://mondaymandala.com/butterfly-coloring-pages/"
work "Nature/Animals/Insects" "https://mondaymandala.com/caterpillar-coloring-pages/"
work "Nature/Animals/Marine" "https://mondaymandala.com/baby-shark-coloring-pages/"
work "Nature/Animals/Marine" "https://mondaymandala.com/dolphin-coloring-pages/"
work "Nature/Animals/Marine" "https://mondaymandala.com/jellyfish-coloring-pages/"
work "Nature/Animals/Marine" "https://mondaymandala.com/octopus-coloring-pages/"
work "Nature/Animals/Marine" "https://mondaymandala.com/shark-coloring-pages/"
work "Nature/Animals/Monkeys" "https://mondaymandala.com/monkey-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/allosaurus-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/ankylosaurus-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/brachiosaurus-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/dinosaur-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/dinosaur-egg-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/gigantosaurus-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/parasaurolophus-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/pterodactyl-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/spinosaurus-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/stegosaurus-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/t-rex-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/triceratops-coloring-pages/"
work "Nature/Animals/Prehistoric" "https://mondaymandala.com/velociraptor-coloring-pages/"
work "Nature/Animals/Reptiles" "https://mondaymandala.com/lizard-coloring-pages/"
work "Nature/Animals/Reptiles" "https://mondaymandala.com/snake-coloring-pages/"
work "Nature/Animals/Rodents" "https://mondaymandala.com/hamster-coloring-pages/"
work "Nature/Animals/Rodents" "https://mondaymandala.com/hedgehog-coloring-pages/"
work "Nature/Animals/Spiders" "https://mondaymandala.com/spider-coloring-pages/"
work "Nature/Crystal" "https://mondaymandala.com/crystal-coloring-pages/"
work "Nature/Mushrooms" "https://mondaymandala.com/mushroom-coloring-pages/"
work "Nature/Plants/Flowers" "https://mondaymandala.com/flower-coloring-pages/"
work "Nature/Plants/Flowers" "https://mondaymandala.com/flower-mandala-coloring-pages/"
work "Nature/Plants/Flowers" "https://mondaymandala.com/tulip-coloring-pages/"
work "Nature/Plants/Succulent" "https://mondaymandala.com/cactus-coloring-pages/"
work "Nature/Plants/Succulent" "https://mondaymandala.com/succulent-coloring-pages/"
work "Nature/Space" "https://mondaymandala.com/solar-system-coloring-pages/"
work "Nature/Weather" "https://mondaymandala.com/tornado-coloring-pages/"
work "Nature/Weather" "https://mondaymandala.com/rain-coloring-pages/"
work "Other/Alvin and the Chipmunks" "https://mondaymandala.com/alvin-and-the-chipmunks-coloring-pages/"
work "Other/Captain Underpants" "https://mondaymandala.com/captain-underpants-coloring-pages/"
work "Other/Care Bears" "https://mondaymandala.com/care-bear-coloring-pages/"
work "Other/Clifford" "https://mondaymandala.com/clifford-coloring-pages/"
work "Other/Goosebumps" "https://mondaymandala.com/goosebumps-coloring-pages/"
work "Other/Magic School Bus" "https://mondaymandala.com/magic-school-bus-coloring-pages/"
work "Other/My Little Pony" "https://mondaymandala.com/fluttershy-coloring-pages/"
work "Other/My Little Pony" "https://mondaymandala.com/my-little-pony-coloring-pages/"
work "Other/My Little Pony" "https://mondaymandala.com/pinkie-pie-coloring-pages/"
work "Other/My Little Pony" "https://mondaymandala.com/princess-celestia-coloring-pages/"
work "Other/My Little Pony" "https://mondaymandala.com/princess-luna-coloring-pages/"
work "Other/My Little Pony" "https://mondaymandala.com/rarity-coloring-pages/"
work "Other/My Little Pony" "https://mondaymandala.com/twilight-sparkle-coloring-pages/"
work "Other/Paddington" "https://mondaymandala.com/paddington-coloring-pages/"
work "Other/Peter Rabbit" "https://mondaymandala.com/peter-rabbit-coloring-pages/"
work "Other/Strawberry Shortcake" "https://mondaymandala.com/strawberry-shortcake-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/bmw-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/corvette-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/dirt-bike-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/excavator-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/jet-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/john-deere-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/rocket-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/tank-coloring-pages/"
work "Other/Vehicles" "https://mondaymandala.com/truck-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/bulbasaur-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/charizard-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/charmander-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/christmas-pokemon-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/eevee-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/halloween-pokemon-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/mewtwo-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/pikachu-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/pokemon-card-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/pokemon-coloring-pages/"
work "Pokemon" "https://mondaymandala.com/squirtle-coloring-pages/"
work "Sanrio/Hello Kitty" "https://mondaymandala.com/hello-kitty-coloring-pages/"
work "Sanrio/Keroppi" "https://mondaymandala.com/keroppi-coloring-pages/"
work "Sanrio/My Melody" "https://mondaymandala.com/my-melody-coloring-pages/"
work "Sanrio/Pompompurin" "https://mondaymandala.com/pompompurin-coloring-pages/"
work "Sanrio/Unsorted" "https://mondaymandala.com/sanrio-coloring-pages/"
work "Sesame Street" "https://mondaymandala.com/kermit-the-frog-coloring-pages/"
work "Sesame Street" "https://mondaymandala.com/muppets-coloring-pages/"
work "Sesame Street" "https://mondaymandala.com/sesame-street-coloring-pages/"
work "Sports/Basketball" "https://mondaymandala.com/basketball-coloring-pages/"
work "Sports/Basketball" "https://mondaymandala.com/steph-curry-coloring-pages/"
work "Sports/Cheerleading" "https://mondaymandala.com/cheerleading-coloring-pages/"
work "Sports/Football" "https://mondaymandala.com/football-coloring-pages/"
work "Sports/Gymnastics" "https://mondaymandala.com/gymnastics-coloring-pages/"
work "Sports/Hockey" "https://mondaymandala.com/hockey-coloring-pages/"
work "Sports/Karate" "https://mondaymandala.com/karate-coloring-pages/"
work "Sports/Soccer" "https://mondaymandala.com/lionel-messi-coloring-pages/"
work "Sports/Soccer" "https://mondaymandala.com/soccer-coloring-pages/"
work "Star Trek" "https://mondaymandala.com/star-trek-coloring-pages/"
work "Star Wars" "https://mondaymandala.com/baby-yoda-coloring-pages/"
work "Star Wars" "https://mondaymandala.com/darth-vader-coloring-pages/"
work "Star Wars" "https://mondaymandala.com/star-wars-coloring-pages/"
work "Toons/Betty Boop" "https://mondaymandala.com/betty-boop-coloring-pages/"
work "Toons/Garfield" "https://mondaymandala.com/garfield-coloring-pages/"
work "Toons/Kuromi" "https://mondaymandala.com/kuromi-coloring-pages/"
work "Toons/Peanuts" "https://mondaymandala.com/snoopy-coloring-pages/"
work "Toons/Popeye" "https://mondaymandala.com/popeye-coloring-pages/"
work "Toons/Pusheen" "https://mondaymandala.com/pusheen-coloring-pages/"
work "Toons/Sumikko Gurashi" "https://mondaymandala.com/sumikko-gurashi-coloring-pages/"
work "Toys/Barbie" "https://mondaymandala.com/barbie-coloring-pages/"
work "Toys/Bratz" "https://mondaymandala.com/bratz-coloring-pages/"
work "Toys/Hot Wheels" "https://mondaymandala.com/hot-wheels-coloring-pages/"
work "Toys/Lego/Avengers" "https://mondaymandala.com/lego-avengers-coloring-pages/"
work "Toys/Lego/Batman" "https://mondaymandala.com/lego-batman-coloring-pages/"
work "Toys/Lego" "https://mondaymandala.com/lego-coloring-pages/"
work "Toys/Lego/Ninjago" "https://mondaymandala.com/lego-ninjago-coloring-pages/"
work "Toys/Littlest Pet Shop" "https://mondaymandala.com/littlest-pet-shop-coloring-pages/"
work "Toys/LOL Surprise" "https://mondaymandala.com/lol-surprise-coloring-pages/"
work "Toys/Polly Pocket" "https://mondaymandala.com/polly-pocket-coloring-pages/"
work "Toys/Shopkins" "https://mondaymandala.com/shopkins-coloring-pages/"
work "Toys/Squishmallow" "https://mondaymandala.com/squishmallow-coloring-pages/"
work "TV Shows/Abby Hatcher" "https://mondaymandala.com/abby-hatcher-coloring-pages/"
work "TV Shows/Addams Family" "https://mondaymandala.com/addams-family-coloring-pages/"
work "TV Shows/Adventure Time" "https://mondaymandala.com/adventure-time-coloring-pages/"
work "TV Shows/Barney" "https://mondaymandala.com/barney-coloring-pages/"
work "TV Shows/Ben 10" "https://mondaymandala.com/ben-10-coloring-pages/"
work "TV Shows/Beyblade" "https://mondaymandala.com/beyblade-coloring-pages/"
work "TV Shows/Blaze The Monster Machine" "https://mondaymandala.com/blaze-coloring-pages/"
work "TV Shows/Blue's Clues" "https://mondaymandala.com/blues-clues-coloring-pages/"
work "TV Shows/Bluey" "https://mondaymandala.com/bluey-coloring-pages/"
work "TV Shows/Bob The Builder" "https://mondaymandala.com/bob-the-builder-coloring-pages/"
work "TV Shows/Booba" "https://mondaymandala.com/booba-coloring-pages/"
work "TV Shows/Bubble Guppies" "https://mondaymandala.com/bubble-guppies-coloring-pages/"
work "TV Shows/CoComelon" "https://mondaymandala.com/cocomelon-coloring-pages/"
work "TV Shows/Curious George" "https://mondaymandala.com/curious-george-coloring-pages/"
work "TV Shows/Daniel Tiger" "https://mondaymandala.com/daniel-tiger-coloring-pages/"
work "TV Shows/Digimon" "https://mondaymandala.com/digimon-coloring-pages/"
work "TV Shows/Dora The Explorer" "https://mondaymandala.com/dora-the-explorer-coloring-pages/"
work "TV Shows/Dragon Ball Z" "https://mondaymandala.com/dragon-ball-z-coloring-pages/"
work "TV Shows/Dragon Ball Z" "https://mondaymandala.com/goku-coloring-pages/"
work "TV Shows/Elena Of Avalor" "https://mondaymandala.com/elena-of-avalor-coloring-pages/"
work "TV Shows/Ever After High" "https://mondaymandala.com/ever-after-high-coloring-pages/"
work "TV Shows/Gabby's Dollhouse" "https://mondaymandala.com/gabbys-dollhouse-coloring-pages/"
work "TV Shows/Gravity Falls" "https://mondaymandala.com/gravity-falls-coloring-pages/"
work "TV Shows/Looney Tunes" "https://mondaymandala.com/looney-tunes-coloring-pages/"
work "TV Shows/Loony Tunes" "https://mondaymandala.com/tweety-bird-coloring-pages/"
work "TV Shows/Masha And The Bear" "https://mondaymandala.com/masha-and-the-bear-coloring-pages/"
work "TV Shows/Miraculous Ladybug" "https://mondaymandala.com/miraculous-ladybug-coloring-pages/"
work "TV Shows/Monster High" "https://mondaymandala.com/monster-high-coloring-pages/"
work "TV Shows/Octonauts" "https://mondaymandala.com/octonauts-coloring-pages/"
work "TV Shows/Palace Pets" "https://mondaymandala.com/palace-pets-coloring-pages/"
work "TV Shows/Paw Patrol" "https://mondaymandala.com/paw-patrol-coloring-pages/"
work "TV Shows/Peppa Pig" "https://mondaymandala.com/peppa-pig-coloring-pages/"
work "TV Shows/Pinkfong" "https://mondaymandala.com/pinkfong-coloring-pages/"
work "TV Shows/PJ Mask" "https://mondaymandala.com/pj-masks-coloring-pages/"
work "TV Shows/PJ Masks" "https://mondaymandala.com/pj-masks-coloring-pages/"
work "TV Shows/Pocoyo" "https://mondaymandala.com/pocoyo-coloring-pages/"
work "TV Shows/Powerpuff Girls" "https://mondaymandala.com/powerpuff-girls-coloring-pages/"
work "TV Shows/Power Rangers" "https://mondaymandala.com/power-rangers-coloring-pages/"
work "TV Shows/Rick and Morty" "https://mondaymandala.com/rick-and-morty-coloring-pages/"
work "TV Shows/Rugrats" "https://mondaymandala.com/rugrats-coloring-pages/"
work "TV Shows/Scooby-Doo" "https://mondaymandala.com/scooby-doo-coloring-pages/"
work "TV Shows/Shimmer And Shine" "https://mondaymandala.com/shimmer-and-shine-coloring-pages/"
work "TV Shows/Smurfs" "https://mondaymandala.com/smurf-coloring-pages/"
work "TV Shows/Sofia The First" "https://mondaymandala.com/sofia-the-first-coloring-pages/"
work "TV Shows/Spirit" "https://mondaymandala.com/spirit-coloring-pages/"
work "TV Shows/SpongeBob" "https://mondaymandala.com/spongebob-coloring-pages/"
work "TV Shows/Steven Universe" "https://mondaymandala.com/steven-universe-coloring-pages/"
work "TV Shows/Stranger Things" "https://mondaymandala.com/stranger-things-coloring-pages/"
work "TV Shows/Tayo" "https://mondaymandala.com/tayo-coloring-pages/"
work "TV Shows/Teen Titans Go" "https://mondaymandala.com/teen-titans-go-coloring-pages/"
work "TV Shows/The Amazing World Of Gumball" "https://mondaymandala.com/amazing-world-of-gumball-coloring-pages/"
work "TV Shows/The Office" "https://mondaymandala.com/the-office-coloring-pages/"
work "TV Shows/Thomas And Friends" "https://mondaymandala.com/thomas-and-friends-coloring-pages/"
work "TV Shows/Tom and Jerry" "https://mondaymandala.com/tom-and-jerry-coloring-pages/"
work "TV Shows/Transformers" "https://mondaymandala.com/rescue-bots-coloring-pages/"
work "TV Shows/Transformers" "https://mondaymandala.com/transformers-coloring-pages/"
work "TV Shows/Vampirina" "https://mondaymandala.com/vampirina-coloring-pages/"
work "TV Shows/Wild Kratts" "https://mondaymandala.com/wild-kratts-coloring-pages/"
work "TV Shows/Winx" "https://mondaymandala.com/winx-coloring-pages/"
work "TV Shows/Yu-Gi-Oh" "https://mondaymandala.com/yu-gi-oh-coloring-pages/"
work "Unsorted/80s" "https://mondaymandala.com/80s-coloring-pages/"
work "Unsorted/Aesthetic" "https://mondaymandala.com/aesthetic-coloring-pages/"
work "Unsorted/Anime" "https://mondaymandala.com/anime-coloring-pages/"
work "Unsorted/Art/Fashion" "https://mondaymandala.com/crown-coloring-pages/"
work "Unsorted/Art/Fashion" "https://mondaymandala.com/wedding-coloring-pages/"
work "Unsorted/Art/Hippie/" "https://mondaymandala.com/boho-coloring-pages/"
work "Unsorted/Astronaut" "https://mondaymandala.com/astronaut-coloring-pages/"
work "Unsorted/Ballerina" "https://mondaymandala.com/ballerina-coloring-pages/"
work "Unsorted/Camping" "https://mondaymandala.com/camping-coloring-pages/"
work "Unsorted/Chibi" "https://mondaymandala.com/chibi-coloring-pages/"
work "Unsorted/Clowns" "https://mondaymandala.com/clown-coloring-pages/"
work "Unsorted/Cowboy" "https://mondaymandala.com/cowboy-coloring-pages/"
work "Unsorted/Cozy" "https://mondaymandala.com/cozy-coloring-pages/"
work "Unsorted/Cute" "https://mondaymandala.com/cute-coloring-pages/"
work "Unsorted/Dancing" "https://mondaymandala.com/dancing-coloring-pages/"
work "Unsorted/Disney/Villains" "https://mondaymandala.com/disney-villain-coloring-pages/"
work "Unsorted/Fantasy/Fairy Tales" "https://mondaymandala.com/fairy-tale-coloring-pages/"
work "Unsorted/Fantasy" "https://mondaymandala.com/fantasy-coloring-pages/"
work "Unsorted/Farm" "https://mondaymandala.com/farm-coloring-pages/"
work "Unsorted/Holiday/Wednesday" "https://mondaymandala.com/wednesday-coloring-pages/"
work "Unsorted/Kawaii" "https://mondaymandala.com/kawaii-coloring-pages/"
work "Unsorted/Magic" "https://mondaymandala.com/magic-coloring-pages/"
work "Unsorted/Moon" "https://mondaymandala.com/moon-coloring-pages/"
work "Unsorted/Nature/Animals" "https://mondaymandala.com/animal-coloring-pages/"
work "Unsorted/Nature/Animals" "https://mondaymandala.com/animal-mandala-coloring-pages/"
work "Unsorted/Nature/Animals" "https://mondaymandala.com/farm-animals-coloring-pages/"
work "Unsorted/Nature/Garden" "https://mondaymandala.com/garden-coloring-pages/"
work "Unsorted/Nature/Jungle" "https://mondaymandala.com/jungle-coloring-pages/"
work "Unsorted/Ninja" "https://mondaymandala.com/ninja-coloring-pages/"
work "Unsorted/Princess" "https://mondaymandala.com/princess-coloring-pages/"
work "Unsorted/Superheroes" "https://mondaymandala.com/superhero-coloring-pages/"
work "Unsorted/Vintage" "https://mondaymandala.com/vintage-coloring-pages/"
#work "Unsorted/Disney/Princess" "https://mondaymandala.com/disney-princess-coloring-pages/"

mkdir -p "Comics/Marvel/Fantastic Four"
mkdir -p "Comics/Marvel/Daredevil"
wget -nc -O "Comics/Marvel/Fantastic FourReed-Richards-Mr.-Fantastic-Coloring-Page-For-Kids.pdf" "https://mondaymandala.com/wp-content/uploads/Reed-Richards-Mr.-Fantastic-Coloring-Page-For-Kids.pdf"
wget -nc -O "Comics/Marvel/Daredevil/Outline-Of-Daredevil-Coloring-Page-For-Kids-1.pdf" "https://mondaymandala.com/wp-content/uploads/Outline-Of-Daredevil-Coloring-Page-For-Kids-1.pdf"
wget -nc -O "Comics/Marvel/Fantastic Four/Ben-Grimm-The-Thing-Coloring-Page-For-Preschoolers.pdf" "https://mondaymandala.com/wp-content/uploads/Ben-Grimm-The-Thing-Coloring-Page-For-Preschoolers.pdf"
wget -nc -O "Comics/Marvel/Avengers/Coloring-Page-Of-Silver-Surfer.pdf" "https://mondaymandala.com/wp-content/uploads/Coloring-Page-Of-Silver-Surfer.pdf"
wget -nc -O "Comics/Marvel/Thor/Coloring-Page-Of-Thor-Surrounded-By-Lightning.pdf" "https://mondaymandala.com/wp-content/uploads/Coloring-Page-Of-Thor-Surrounded-By-Lightning.pdf"
wget -nc -O "Comics/Marvel/Avengers/Hawkeye-Clint-Barton-Coloring-Page.pdf" "https://mondaymandala.com/wp-content/uploads/Hawkeye-Clint-Barton-Coloring-Page.pdf"
wget -nc -O "Comics/DC/Justice League/Coloring-Page-Of-Justice-League-Cyborg.pdf" "https://mondaymandala.com/wp-content/uploads/Coloring-Page-Of-Justice-League-Cyborg.pdf"
wget -nc -O "Comics/DC/Supergirl/Coloring-Page-Of-Supergirl-Flying-In-The-City.pdf" "https://mondaymandala.com/wp-content/uploads/Coloring-Page-Of-Supergirl-Flying-In-The-City.pdf"
wget -nc -O "Comics/DC/Green Lantern/Green-Lantern-Fighting-Coloring-Page.pdf" "https://mondaymandala.com/wp-content/uploads/Green-Lantern-Fighting-Coloring-Page.pdf"
wget -nc -O "Comics/DC/Flash/The-Flash-Running-Coloring-Page.pdf" "https://mondaymandala.com/wp-content/uploads/The-Flash-Running-Coloring-Page.pdf"
